bootstrap.servers=pkc-56d1g.eastus.azure.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN

# sasl.username and sasl.password are read from environment variables
# SASL_USERNAME and SASL_PASSWORD (set in .env)

# Best practice for Kafka producer to prevent data loss
acks=all
