version: '3.8'
services:
  api:
    container_name: confluent-kafka-consumer-net
    build:
      context: ./
    image: confluent-kafka-consumer-net:latest
    ports:
      - "8080:8080"
    environment:
      RPCENDPOINT: ${RPCENDPOINT}
    networks:
      confluent_kafka_net:
        ipv4_address: 172.28.1.12
volumes:
  db:
    driver: local
networks:
  confluent_kafka_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
